import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "submit_step1_ceiling",
            "description": "Only authors of the submission may submit step-1 material while step 1 is open.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"submitStep1"',
            "resource_type": "Submission",
            "reference_path": os.path.join(REFS, "submit_step1_ceiling.cedar"),
        },
        {
            "name": "submit_full_paper_ceiling",
            "description": "Only authors with step-2 credentials may upload full papers during step 2.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"submitFullPaper"',
            "resource_type": "Submission",
            "reference_path": os.path.join(REFS, "submit_full_paper_ceiling.cedar"),
        },
        {
            "name": "update_step1_ceiling",
            "description": "Only authors with step-2 credentials may correct step-1 information during step 2.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"updateStep1Info"',
            "resource_type": "Submission",
            "reference_path": os.path.join(REFS, "update_step1_ceiling.cedar"),
        },
        {
            "name": "camera_ready_ceiling",
            "description": "Only authors of selected submissions may submit camera-ready versions after review.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"submitCameraReady"',
            "resource_type": "Submission",
            "reference_path": os.path.join(REFS, "camera_ready_ceiling.cedar"),
        },
        {
            "name": "download_assigned_ceiling",
            "description": "Only assigned non-conflicted reviewers may download papers after distribution.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"downloadPaper"',
            "resource_type": "Submission",
            "reference_path": os.path.join(REFS, "download_assigned_ceiling.cedar"),
        },
        {
            "name": "display_abstract_ceiling",
            "description": "Only assigned non-conflicted reviewers may display abstracts after distribution.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"displayAbstract"',
            "resource_type": "Submission",
            "reference_path": os.path.join(REFS, "display_abstract_ceiling.cedar"),
        },
        {
            "name": "submit_review_ceiling",
            "description": "Only assigned non-conflicted reviewers may submit reviews while review is open.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"submitReview"',
            "resource_type": "Submission",
            "reference_path": os.path.join(REFS, "submit_review_ceiling.cedar"),
        },
        {
            "name": "update_review_ceiling",
            "description": "Only assigned non-conflicted reviewers may update reviews while review is open.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"updateReview"',
            "resource_type": "Submission",
            "reference_path": os.path.join(REFS, "update_review_ceiling.cedar"),
        },
        {
            "name": "read_other_reviews_ceiling",
            "description": "Reviewers may read other reviews only after submitting their own review for the paper.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"readOtherReviews"',
            "resource_type": "Submission",
            "reference_path": os.path.join(REFS, "read_other_reviews_ceiling.cedar"),
        },
        {
            "name": "volunteer_conflicting_paper_ceiling",
            "description": "Reviewers may volunteer for conflicting-review papers only after finishing assigned reviews and absent conflict of interest.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"volunteerForConflictingPaper"',
            "resource_type": "Submission",
            "reference_path": os.path.join(REFS, "volunteer_conflicting_paper_ceiling.cedar"),
        },
        {
            "name": "monitor_ceiling",
            "description": "Only chair/PCC roles may monitor review overviews.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"monitorReviewProcess"',
            "resource_type": "ReviewOverview",
            "reference_path": os.path.join(REFS, "monitor_ceiling.cedar"),
        },
        {
            "name": "ask_additional_reviewer_ceiling",
            "description": "Only PCC may ask additional reviewers for low-expertise papers.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"askAdditionalReviewer"',
            "resource_type": "ReviewOverview",
            "reference_path": os.path.join(REFS, "ask_additional_reviewer_ceiling.cedar"),
        },
        {
            "name": "directory_access_ceiling",
            "description": "Reviewer directories are protected by owner or allowed-user list.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"accessReviewerDirectory"',
            "resource_type": "ReviewerDirectory",
            "reference_path": os.path.join(REFS, "directory_access_ceiling.cedar"),
        },
        {
            "name": "review_file_access_ceiling",
            "description": "Review files are protected by the file and directory allowed-user lists.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"readReviewFile"',
            "resource_type": "ReviewFile",
            "reference_path": os.path.join(REFS, "review_file_access_ceiling.cedar"),
        },
        {
            "name": "author_submit_step1_floor",
            "description": "Authors must be able to submit step-1 material during step 1.",
            "type": "floor",
            "principal_type": "User",
            "action": 'Action::"submitStep1"',
            "resource_type": "Submission",
            "floor_path": os.path.join(REFS, "author_submit_step1_floor.cedar"),
        },
        {
            "name": "reviewer_read_other_reviews_floor",
            "description": "A reviewer who has submitted their own review must be able to read other reviews for that paper.",
            "type": "floor",
            "principal_type": "User",
            "action": 'Action::"readOtherReviews"',
            "resource_type": "Submission",
            "floor_path": os.path.join(REFS, "reviewer_read_other_reviews_floor.cedar"),
        },
        {
            "name": "pcc_ask_additional_reviewer_floor",
            "description": "PCC must be able to ask for additional review on low-expertise papers.",
            "type": "floor",
            "principal_type": "User",
            "action": 'Action::"askAdditionalReviewer"',
            "resource_type": "ReviewOverview",
            "floor_path": os.path.join(REFS, "pcc_ask_additional_reviewer_floor.cedar"),
        },
        {
            "name": "liveness_submit_step1",
            "description": "At least one author step-1 submission request should be possible.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": 'Action::"submitStep1"',
            "resource_type": "Submission",
        },
        {
            "name": "liveness_submit_review",
            "description": "At least one reviewer submit-review request should be possible.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": 'Action::"submitReview"',
            "resource_type": "Submission",
        },
        {
            "name": "liveness_monitor",
            "description": "At least one chair/PCC monitoring request should be possible.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": 'Action::"monitorReviewProcess"',
            "resource_type": "ReviewOverview",
        },
    ]

