"""Provider-neutral backends, configuration, and credential storage."""

from autocedar.providers.base import (
    BackendUnavailableError,
    ChatMessage,
    InstructionPart,
    ModelBackend,
    ModelUsage,
    ProviderConfigurationError,
    ProviderError,
    StructuredResult,
    TextResult,
)
from autocedar.providers.config import (
    CANONICAL_PROVIDER_IDS,
    DEFAULT_LOCAL_BASE_URL,
    DEFAULT_MODELS,
    PROVIDER_ALIASES,
    REASONING_EFFORTS,
    ProviderOptions,
    ProviderSettings,
    ResolvedProviderConfig,
    SessionOverrides,
    SettingsStore,
    canonical_provider_id,
    config_directory,
    legacy_env_path,
    resolve_provider_config,
    settings_path,
)
from autocedar.providers.auth import (
    AuthStore,
    ProviderAuth,
    ProviderCredential,
    ResolvedCredential,
    auth_path,
    resolve_api_key,
)
from autocedar.providers.registry import (
    DEFAULT_REGISTRY,
    ProviderDefinition,
    ProviderRegistry,
    create_backend,
    get_provider_definition,
)

__all__ = [
    "BackendUnavailableError",
    "AuthStore",
    "CANONICAL_PROVIDER_IDS",
    "ChatMessage",
    "DEFAULT_LOCAL_BASE_URL",
    "DEFAULT_MODELS",
    "DEFAULT_REGISTRY",
    "InstructionPart",
    "ModelBackend",
    "ModelUsage",
    "ProviderConfigurationError",
    "PROVIDER_ALIASES",
    "REASONING_EFFORTS",
    "ProviderAuth",
    "ProviderCredential",
    "ProviderDefinition",
    "ProviderError",
    "ProviderOptions",
    "ProviderRegistry",
    "ProviderSettings",
    "ResolvedCredential",
    "ResolvedProviderConfig",
    "SessionOverrides",
    "SettingsStore",
    "StructuredResult",
    "TextResult",
    "canonical_provider_id",
    "config_directory",
    "auth_path",
    "create_backend",
    "get_provider_definition",
    "legacy_env_path",
    "resolve_api_key",
    "resolve_provider_config",
    "settings_path",
]
