import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "catalogue_ceiling",
            "description": "Students may request catalogues from the campus LAN at the beginning of semester.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"requestCatalogue"',
            "resource_type": "CourseCatalogue",
            "reference_path": os.path.join(REFS, "catalogue_ceiling.cedar"),
        },
        {
            "name": "register_course_ceiling",
            "description": "Students may register only for their own current-semester selections while registration is open.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"registerCourse"',
            "resource_type": "CourseSelection",
            "reference_path": os.path.join(REFS, "register_course_ceiling.cedar"),
        },
        {
            "name": "add_course_ceiling",
            "description": "Students may add only their own current selections during add/drop while registration is open.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"addCourseSelection"',
            "resource_type": "CourseSelection",
            "reference_path": os.path.join(REFS, "add_course_ceiling.cedar"),
        },
        {
            "name": "update_course_ceiling",
            "description": "Students may update only their own current selections during add/drop while registration is open.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"updateCourseSelection"',
            "resource_type": "CourseSelection",
            "reference_path": os.path.join(REFS, "update_course_ceiling.cedar"),
        },
        {
            "name": "delete_course_ceiling",
            "description": "Students may delete only their own current selections during add/drop while registration is open.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"deleteCourseSelection"',
            "resource_type": "CourseSelection",
            "reference_path": os.path.join(REFS, "delete_course_ceiling.cedar"),
        },
        {
            "name": "report_card_ceiling",
            "description": "Students may view only their own previous-semester report cards from the campus LAN.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"viewReportCard"',
            "resource_type": "ReportCard",
            "reference_path": os.path.join(REFS, "report_card_ceiling.cedar"),
        },
        {
            "name": "select_teaching_ceiling",
            "description": "Professors may select eligible upcoming offerings only while registration is open and conflict-free.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"selectTeachingOffering"',
            "resource_type": "CourseOffering",
            "reference_path": os.path.join(REFS, "select_teaching_ceiling.cedar"),
        },
        {
            "name": "modify_assigned_offering_ceiling",
            "description": "Professors may modify only their own assigned offerings while registration is open.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"modifyAssignedOffering"',
            "resource_type": "CourseOffering",
            "reference_path": os.path.join(REFS, "modify_assigned_offering_ceiling.cedar"),
        },
        {
            "name": "view_roster_ceiling",
            "description": "Professors may view rosters only for offerings they teach.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"viewRoster"',
            "resource_type": "CourseOffering",
            "reference_path": os.path.join(REFS, "view_roster_ceiling.cedar"),
        },
        {
            "name": "enter_grade_ceiling",
            "description": "Only the professor for a completed previous-semester class may enter grades.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"enterGrade"',
            "resource_type": "GradeRecord",
            "reference_path": os.path.join(REFS, "enter_grade_ceiling.cedar"),
        },
        {
            "name": "student_info_ceiling",
            "description": "Only the registrar may change student information.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"changeStudentInfo"',
            "resource_type": "StudentInfo",
            "reference_path": os.path.join(REFS, "student_info_ceiling.cedar"),
        },
        {
            "name": "close_registration_ceiling",
            "description": "Only the registrar may close current registration.",
            "type": "implies",
            "principal_type": "User",
            "action": 'Action::"closeRegistration"',
            "resource_type": "RegistrationProcess",
            "reference_path": os.path.join(REFS, "close_registration_ceiling.cedar"),
        },
        {
            "name": "register_course_floor",
            "description": "Students must be able to register for their own current-semester offering while registration is open.",
            "type": "floor",
            "principal_type": "User",
            "action": 'Action::"registerCourse"',
            "resource_type": "CourseSelection",
            "floor_path": os.path.join(REFS, "register_course_floor.cedar"),
        },
        {
            "name": "add_course_floor",
            "description": "Students must be able to add their own current selections during add/drop.",
            "type": "floor",
            "principal_type": "User",
            "action": 'Action::"addCourseSelection"',
            "resource_type": "CourseSelection",
            "floor_path": os.path.join(REFS, "add_course_floor.cedar"),
        },
        {
            "name": "report_card_floor",
            "description": "Students must be able to view their own previous-semester report cards.",
            "type": "floor",
            "principal_type": "User",
            "action": 'Action::"viewReportCard"',
            "resource_type": "ReportCard",
            "floor_path": os.path.join(REFS, "report_card_floor.cedar"),
        },
        {
            "name": "select_teaching_floor",
            "description": "Eligible professors must be able to select conflict-free upcoming offerings before registration closes.",
            "type": "floor",
            "principal_type": "User",
            "action": 'Action::"selectTeachingOffering"',
            "resource_type": "CourseOffering",
            "floor_path": os.path.join(REFS, "select_teaching_floor.cedar"),
        },
        {
            "name": "enter_grade_floor",
            "description": "Professors must be able to enter grades for their completed classes.",
            "type": "floor",
            "principal_type": "User",
            "action": 'Action::"enterGrade"',
            "resource_type": "GradeRecord",
            "floor_path": os.path.join(REFS, "enter_grade_floor.cedar"),
        },
        {
            "name": "registrar_close_floor",
            "description": "Registrar must be able to close current registration.",
            "type": "floor",
            "principal_type": "User",
            "action": 'Action::"closeRegistration"',
            "resource_type": "RegistrationProcess",
            "floor_path": os.path.join(REFS, "registrar_close_floor.cedar"),
        },
        {
            "name": "liveness_register",
            "description": "At least one student registration request should be possible.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": 'Action::"registerCourse"',
            "resource_type": "CourseSelection",
        },
        {
            "name": "liveness_enter_grade",
            "description": "At least one professor grade-entry request should be possible.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": 'Action::"enterGrade"',
            "resource_type": "GradeRecord",
        },
        {
            "name": "liveness_close_registration",
            "description": "At least one registrar close-registration request should be possible.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": 'Action::"closeRegistration"',
            "resource_type": "RegistrationProcess",
        },
    ]

